# Generated by Django 6.0.3 on 2026-03-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Transformer Architecture Series'", max_length=200)),
                ('description', models.TextField(help_text='A paragraph describing what this series covers.')),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover image shown on the series card.', null=True, upload_to='series/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Series',
                'verbose_name_plural': 'Blog Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly ID. In Django Admin, click the magic wand to auto-fill from title.', max_length=300, unique=True)),
                ('content', models.TextField(help_text='Write in Markdown. Code blocks with ``` are syntax-highlighted in React.')),
                ('excerpt', models.TextField(blank=True, default='', help_text='1-2 sentence preview shown in blog listing cards.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the series. 1 = first, 2 = second, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(help_text='Which series does this post belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogseries')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
