# Generated by Django 6.0.3 on 2026-03-08 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.FileField(help_text='Upload your image file (PNG, JPG, GIF, WebP, SVG)', upload_to='blog_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp'])]),
        ),
    ]
